### ISSUE TITLE
Tabs/spaces error

### ISSUE THREAD

**Issue by nschneid** [nert-gu/Xposition#1]
https://github.com/nert-gu/Xposition/blob/7a394f6ef96585b40d44a7185128f766582233aa/wiki/plugins/categories/views.py mixes tabs and spaces. I get:

```
$ python manage.py runserver
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x10788b8c8>
Traceback (most recent call last):
  File "/Users/ns1057/anaconda/lib/python3.6/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/Users/ns1057/anaconda/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/Users/ns1057/anaconda/lib/python3.6/site-packages/django/core/management/base.py", line 374, in check
    include_deployment_checks=include_deployment_checks,
  File "/Users/ns1057/anaconda/lib/python3.6/site-packages/django/core/management/base.py", line 361, in _run_checks
    return checks.run_checks(**kwargs)
  File "/Users/ns1057/anaconda/lib/python3.6/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/Users/ns1057/anaconda/lib/python3.6/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/Users/ns1057/anaconda/lib/python3.6/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/Users/ns1057/anaconda/lib/python3.6/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/ns1057/anaconda/lib/python3.6/site-packages/django/urls/resolvers.py", line 313, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/ns1057/anaconda/lib/python3.6/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/ns1057/anaconda/lib/python3.6/site-packages/django/urls/resolvers.py", line 306, in urlconf_module
    return import_module(self.urlconf_name)
  File "/Users/ns1057/anaconda/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/Users/nathan/dev/e/Xposition/testproject/testproject/urls.py", line 10, in <module>
    from wiki.urls import get_pattern as get_wiki_pattern
  File "/Users/nathan/dev/e/Xposition/testproject/wiki/urls.py", line 262, in <module>
    load_wiki_plugins()
  File "/Users/nathan/dev/e/Xposition/testproject/wiki/core/plugins/loader.py", line 49, in load_wiki_plugins
    load('wiki_plugin', verbose=False, failfast=False)
  File "/Users/nathan/dev/e/Xposition/testproject/wiki/core/plugins/loader.py", line 45, in load
    get_module(app, modname, verbose, failfast)
  File "/Users/nathan/dev/e/Xposition/testproject/wiki/core/plugins/loader.py", line 26, in get_module
    module = import_module(module_name)
  File "/Users/ns1057/anaconda/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/nathan/dev/e/Xposition/testproject/wiki/plugins/categories/wiki_plugin.py", line 11, in <module>
    from . import views, settings, forms, models
  File "/Users/nathan/dev/e/Xposition/testproject/wiki/plugins/categories/views.py", line 167
    self.categories = Category.objects.all()
                                           ^
TabError: inconsistent use of tabs and spaces in indentation
```

**Comment by nschneid** [comment]
Also applies to https://github.com/nert-gu/Xposition/blob/7a394f6ef96585b40d44a7185128f766582233aa/wiki/plugins/categories/forms.py

**Comment by nschneid** [comment]
still getting this error

**Comment by jcl240** [comment]
Fixed in [this](https://github.com/nert-gu/Xposition/commit/b26194112b731a39f083b9a148edc57fb551b20e) commit
