### ISSUE TITLE
Migration error

### ISSUE THREAD

**Issue by nschneid** [nert-gu/Xposition#2]
After fixing #1 locally, I get:

```
Traceback (most recent call last):
  File "/Users/ns1057/anaconda/lib/python3.6/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/Users/ns1057/anaconda/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 124, in inner_run
    self.check_migrations()
  File "/Users/ns1057/anaconda/lib/python3.6/site-packages/django/core/management/base.py", line 437, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/Users/ns1057/anaconda/lib/python3.6/site-packages/django/db/migrations/executor.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/Users/ns1057/anaconda/lib/python3.6/site-packages/django/db/migrations/loader.py", line 52, in __init__
    self.build_graph()
  File "/Users/ns1057/anaconda/lib/python3.6/site-packages/django/db/migrations/loader.py", line 268, in build_graph
    raise exc
  File "/Users/ns1057/anaconda/lib/python3.6/site-packages/django/db/migrations/loader.py", line 238, in build_graph
    self.graph.validate_consistency()
  File "/Users/ns1057/anaconda/lib/python3.6/site-packages/django/db/migrations/graph.py", line 261, in validate_consistency
    [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
  File "/Users/ns1057/anaconda/lib/python3.6/site-packages/django/db/migrations/graph.py", line 261, in <listcomp>
    [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
  File "/Users/ns1057/anaconda/lib/python3.6/site-packages/django/db/migrations/graph.py", line 104, in raise_error
    raise NodeNotFoundError(self.error_message, self.key, origin=self.origin)
django.db.migrations.exceptions.NodeNotFoundError: Migration wiki.0003_article_categories dependencies reference nonexistent parent node ('categories', '0002_auto_20170208_1543')
```

**Comment by jcl240** [comment]
See this [https://github.com/nert-gu/Xposition/commit/edfd41705c30a2e6923449ce49f60003f2e2c764](commit)
