### ISSUE TITLE
Trouble with Import-Export

### ISSUE THREAD

**Issue by ablodge** [nert-gu/Xposition#49]
I get the following error when using import-export in admin view on an Excel file.

```
Line number: 1 - 'NoneType' object has no attribute 'DoesNotExist' 
streusle, 4.1, reviews-001325-0001, English, , False, reviews-001325, Highly recommended, 'Highly', 'recommended', , , , Highly recommended
Traceback (most recent call last):
File "c:\users\austin\src\django-import-export\import_export\instance_loaders.py", line 31, in get_instance
field = self.resource.fields[key]
KeyError: 'id'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "c:\users\austin\src\django-import-export\import_export\resources.py", line 453, in import_row
instance, new = self.get_or_init_instance(instance_loader, row)
File "c:\users\austin\src\django-import-export\import_export\resources.py", line 267, in get_or_init_instance
instance = self.get_instance(instance_loader, row)
File "c:\users\austin\src\django-import-export\import_export\resources.py", line 261, in get_instance
return instance_loader.get_instance(row)
File "c:\users\austin\src\django-import-export\import_export\instance_loaders.py", line 34, in get_instance
except self.resource._meta.model.DoesNotExist:
AttributeError: 'NoneType' object has no attribute 'DoesNotExist'
```

**Comment by ablodge** [comment]
No. Could 'id' be an `import-export` variable?

**Comment by nschneid** [comment]
https://github.com/django-import-export/django-import-export/issues/211

**Comment by ablodge** [comment]
Update

```
Line number: 1 - 'NoneType' object has no attribute 'DoesNotExist' 
None, streusle, 4.1, reviews-001325-0001, English, None, False, reviews-001325, Highly recommended, 'Highly', 'recommended', None, None, None, Highly recommended
Traceback (most recent call last):
File "c:\users\austin\src\django-import-export\import_export\instance_loaders.py", line 33, in get_instance
return self.get_queryset().get(**params)
File "c:\users\austin\src\django-import-export\import_export\instance_loaders.py", line 25, in get_queryset
return self.resource._meta.model.objects.all()
AttributeError: 'NoneType' object has no attribute 'objects'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "c:\users\austin\src\django-import-export\import_export\resources.py", line 453, in import_row
instance, new = self.get_or_init_instance(instance_loader, row)
File "c:\users\austin\src\django-import-export\import_export\resources.py", line 267, in get_or_init_instance
instance = self.get_instance(instance_loader, row)
File "c:\users\austin\src\django-import-export\import_export\resources.py", line 261, in get_instance
return instance_loader.get_instance(row)
File "c:\users\austin\src\django-import-export\import_export\instance_loaders.py", line 34, in get_instance
except self.resource._meta.model.DoesNotExist:
AttributeError: 'NoneType' object has no attribute 'DoesNotExist'
```

**Comment by ablodge** [comment]
Update
```
Line number: 1 - get() keywords must be strings 
None, streusle, 4.1, reviews-001325-0001, English, None, False, reviews-001325, Highly recommended, 'Highly', 'recommended', None, None, None, Highly recommended
Traceback (most recent call last):
File "c:\users\austin\src\django-import-export\import_export\resources.py", line 453, in import_row
instance, new = self.get_or_init_instance(instance_loader, row)
File "c:\users\austin\src\django-import-export\import_export\resources.py", line 267, in get_or_init_instance
instance = self.get_instance(instance_loader, row)
File "c:\users\austin\src\django-import-export\import_export\resources.py", line 261, in get_instance
return instance_loader.get_instance(row)
File "c:\users\austin\src\django-import-export\import_export\instance_loaders.py", line 33, in get_instance
return self.get_queryset().get(**params)
TypeError: get() keywords must be strings
```

**Comment by ablodge** [comment]
The function causing the error:
```
def get_instance(self, row):
        try:
            params = {}
            for key in self.resource.get_import_id_fields():
                field = self.resource.fields[key]
                params[field.attribute] = field.clean(row)
            return self.get_queryset().get(**params)
        except self.resource._meta.model.DoesNotExist:
            return None
```

**Comment by ablodge** [comment]
New exception, (I call that progress!):
```
Line number: 2 - UNIQUE constraint failed: metadata_corpussentence.corpus_id, metadata_corpussentence.sent_id 
streusle, 4.1, reviews-001325-0002, English, , False, reviews-001325, My 8 year old daughter loves this place., 'My', '8', 'year', 'old', 'daughter', 'loves', 'this', 'place', '.', , , , My 8 year_old daughter loves this place .
Traceback (most recent call last):
File "C:\Users\Austin\Anaconda3\lib\site-packages\django\db\backends\utils.py", line 64, in execute
return self.cursor.execute(sql, params)
File "C:\Users\Austin\Anaconda3\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: UNIQUE constraint failed: metadata_corpussentence.corpus_id, metadata_corpussentence.sent_id
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "c:\users\austin\src\django-import-export\import_export\resources.py", line 475, in import_row
self.save_instance(instance, using_transactions, dry_run)
File "c:\users\austin\src\django-import-export\import_export\resources.py", line 285, in save_instance
instance.save()
File "C:\Users\Austin\Anaconda3\lib\site-packages\django\db\models\base.py", line 808, in save
force_update=force_update, update_fields=update_fields)
File "C:\Users\Austin\Anaconda3\lib\site-packages\django\db\models\base.py", line 838, in save_base
updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
File "C:\Users\Austin\Anaconda3\lib\site-packages\django\db\models\base.py", line 924, in _save_table
result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
File "C:\Users\Austin\Anaconda3\lib\site-packages\django\db\models\base.py", line 963, in _do_insert
using=using, raw=raw)
File "C:\Users\Austin\Anaconda3\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
return getattr(self.get_queryset(), name)(*args, **kwargs)
File "C:\Users\Austin\Anaconda3\lib\site-packages\django\db\models\query.py", line 1076, in _insert
return query.get_compiler(using=using).execute_sql(return_id)
File "C:\Users\Austin\Anaconda3\lib\site-packages\django\db\models\sql\compiler.py", line 1112, in execute_sql
cursor.execute(sql, params)
File "C:\Users\Austin\Anaconda3\lib\site-packages\django\db\backends\utils.py", line 79, in execute
return super(CursorDebugWrapper, self).execute(sql, params)
File "C:\Users\Austin\Anaconda3\lib\site-packages\django\db\backends\utils.py", line 64, in execute
return self.cursor.execute(sql, params)
File "C:\Users\Austin\Anaconda3\lib\site-packages\django\db\utils.py", line 94, in __exit__
six.reraise(dj_exc_type, dj_exc_value, traceback)
File "C:\Users\Austin\Anaconda3\lib\site-packages\django\utils\six.py", line 685, in reraise
raise value.with_traceback(tb)
File "C:\Users\Austin\Anaconda3\lib\site-packages\django\db\backends\utils.py", line 64, in execute
return self.cursor.execute(sql, params)
File "C:\Users\Austin\Anaconda3\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: UNIQUE constraint failed: metadata_corpussentence.corpus_id, metadata_corpussentence.sent_id
```

**Comment by ablodge** [comment]
Mystery:

> We couldn’t find any code matching 'corpus_id' in nert-gu/Xposition

**Comment by nschneid** [comment]
GitHub search only looks in the master branch.

**Comment by ablodge** [comment]
I didn't create a `corpus_id` field. Could django or the import-export plugin have made the field automatically?

**Comment by nschneid** [comment]
If there's an `id` field in the `Corpus` model, it could be that the underlying field name in the database is `corpus_id` or even `metadata_corpus_id`.
