### ISSUE TITLE
Don't create a category when creating an adposition or usage

### ISSUE THREAD

**Issue by nschneid** [nert-gu/Xposition#97]
I tried truncating the list of categories loaded in the sidebar (https://github.com/nert-gu/Xposition/issues/96#issuecomment-405752154) and that made the Edit Article page load way faster. E.g.

```py
self.fields['categories'].queryset = ArticleCategory.objects.filter(id__lt=100)
```

with just 100 categories loaded is pretty fast. So not creating adposition/usage categories should help. We can keep automatic categories for supersenses; I don't know about construals.

Please create a separate branch (off wiki-data) for this change.

**Comment by ablodge** [comment]
Trying to create a usage with no category:

> A server error occurred.  Please contact the administrator.

**Comment by ablodge** [comment]
```
Traceback (most recent call last):
  File "C:\Users\Austin\Anaconda3\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\Austin\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "C:\Users\Austin\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Austin\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Austin\Anaconda3\lib\site-packages\django\contrib\admin\options.py", line 551, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\Austin\Anaconda3\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Austin\Anaconda3\lib\site-packages\django\views\decorators\cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Austin\Anaconda3\lib\site-packages\django\contrib\admin\sites.py", line 224, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\Austin\Anaconda3\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "C:\Users\Austin\Anaconda3\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Austin\Anaconda3\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "C:\Users\Austin\Anaconda3\lib\site-packages\django\contrib\admin\options.py", line 1584, in changelist_view
    response = self.response_action(request, queryset=cl.get_queryset(request))
  File "C:\Users\Austin\Anaconda3\lib\site-packages\django\contrib\admin\options.py", line 1286, in response_action
    response = func(self, request, queryset)
  File "C:\Users\Austin\Anaconda3\lib\site-packages\mptt\admin.py", line 85, in delete_selected_tree
    obj_display = force_text(obj)
  File "C:\Users\Austin\Anaconda3\lib\site-packages\django\utils\encoding.py", line 76, in force_text
    s = six.text_type(s)
  File "C:\Users\Austin\Desktop\Xposition\local\Xposition\testproject\wiki\models\urlpath.py", line 192, in __str__
    path = self.path
  File "C:\Users\Austin\Desktop\Xposition\local\Xposition\testproject\wiki\models\urlpath.py", line 133, in path
    self.cached_ancestors))
  File "C:\Users\Austin\Desktop\Xposition\local\Xposition\testproject\wiki\models\urlpath.py", line 107, in __cached_ancestors
    if not self.get_ancestors().exists():
  File "C:\Users\Austin\Anaconda3\lib\site-packages\mptt\models.py", line 395, in _fn
    % {'function': func.__name__, 'class': self.__class__.__name__}
ValueError: Cannot call get_ancestors on unsaved URLPath instances

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Austin\Anaconda3\lib\wsgiref\handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "C:\Users\Austin\Anaconda3\lib\site-packages\django\core\handlers\wsgi.py", line 157, in __call__
    response = self.get_response(request)
  File "C:\Users\Austin\Anaconda3\lib\site-packages\django\core\handlers\base.py", line 124, in get_response
    response = self._middleware_chain(request)
  File "C:\Users\Austin\Anaconda3\lib\site-packages\django\core\handlers\exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "C:\Users\Austin\Anaconda3\lib\site-packages\django\core\handlers\exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "C:\Users\Austin\Anaconda3\lib\site-packages\django\core\handlers\exception.py", line 143, in handle_uncaught_exception
    return callback(request, **param_dict)
  File "C:\Users\Austin\Anaconda3\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Austin\Desktop\Xposition\local\Xposition\testproject\testproject\views.py", line 17, in server_error
    'request': request,
  File "C:\Users\Austin\Anaconda3\lib\site-packages\django\template\backends\django.py", line 64, in render
    context = make_context(context, request, autoescape=self.backend.engine.autoescape)
  File "C:\Users\Austin\Anaconda3\lib\site-packages\django\template\context.py", line 287, in make_context
    raise TypeError('context must be a dict rather than %s.' % context.__class__.__name__)
TypeError: context must be a dict rather than RequestContext.
```

**Comment by ablodge** [comment]
Alright, I've got it working.
@nschneid I recommend you test it too. Try creating a few objects and look at the site's categories. I'll send you a db.
